### ISSUE TITLE
the app does not work on fedora silverblue

### ISSUE THREAD

**Issue by dinhokusanagi** [flathub/org.wireshark.Wireshark#66] opened 2021-09-19 12:15 UTC
![Captura de tela de 2021-09-19 09-13-24](https://user-images.githubusercontent.com/43162113/133927077-0b7bfcba-39b4-496a-98a6-c9c1012e1d0f.png)
![Captura de Tela-20210919091408-708x509](https://user-images.githubusercontent.com/43162113/133927080-9b2b3e55-75a8-4d4b-a385-d95ca2a9e054.png)

**Comment by alcir** [comment] 2021-11-19 14:17
https://github.com/flathub/org.wireshark.Wireshark/issues/4

In addition. Flatpaks are sandboxed, but you are executing such command on the host. Last but not least, eventually, dpkg-reconfigure is a Debian/Ubuntu command that will never work on Fedora Linux, also on regular Workstation.

**Comment by muelli** [comment] 2022-03-18 09:16
closing as duplicate of #4.

**Closed by muelli** 2022-03-18 09:16 UTC

**Comment by dinhokusanagi** [comment] 2022-04-28 03:29
> [#4 ](https://github.com/flathub/org.wireshark.Wireshark/issues/4)
> 
> Além disso. Flatpaks são sandbox, mas você está executando esse comando no host. Por último, mas não menos importante, eventualmente, dpkg-reconfigure é um comando Debian/Ubuntu que nunca funcionará no Fedora Linux, também em Workstation normal.

This I know, the question the developers do not know this? is known why it puts a false instruction to the user?

**Comment by dinhokusanagi** [comment] 2022-04-28 03:32
> closing as duplicate of #4.

In short, they didn't find a solution to make it work and it's still on the flathub.
